# Generated by Django 4.0.2 on 2022-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='destination',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
