# Generated by Django 4.0.2 on 2022-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appuser_category_alter_appuser_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
