# Generated by Django 4.0.2 on 2022-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appuser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
