# Generated by Django 4.0.2 on 2022-02-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appuser_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='price',
        ),
    ]
